import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <title>Guildly</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:site_name" content="Guildly" />
      <meta
        property="og:title"
        content="Guildly - Protocol for Sharing NFTs and Gameplay"
      />
      <meta property="og:type" content="website" />
      <meta
        property="og:description"
        content="Guildly is a decentralized protocol that allows for the management of shared accounts and the sharing of NFT assets in Web 3.0 games."
      />
      <meta property="og:url" content="%PUBLIC_URL%" />
      <meta property="og:image" content="%PUBLIC_URL%/guildly-logo.png" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Neuton:ital,wght@0,200;0,300;0,400;0,700;0,800;1,400&display=swap"
        rel="stylesheet"
      />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
